@extends('layouts.app')

@section('content')
<header class="header">
    <div class="container">
    <div class="row align-items-center h-100">

        <div class="col-md-7 mx-auto">
        <h1>Terms and Conditions</h1>

        <p>These Terms and Conditions govern the service provided by the owner of the website viralget.com.ng to visitors and users of the site. Use of the service provided by this website implies full acceptance of these Terms and Conditions.</p>

            <p>1. IDENTIFICATION OF PARTIES 1.1. On one side, the company Viral Get, Owner of the site viralget.com.ng, placed at 168c, Ekoro Road, Opp. Foursquare Gospel Church, Abule-Egba Lagos State, Nigeria, registered in the Corporate Affairs Commission established under the Companies and Allied Matters Act 1990, and with the email address info@viralget.com.ng (hereinafter referred to as VIRAL GET). 1.2. And on the other side, the viralget.com.ng website visitor that uses the services provided in the aforementioned website or get by User registration the status of USER (hereinafter referred to as the USER). 2. TERMS OF USE OF THE SERVICE 1.3. The User must be at least 18 years sufficient capacity to contract and shall fully and unreservedly accept all these Terms and Conditions. 1.4. Also, in order to use the Service is necessary that the user holds an account at www.twitter.com (or authorized by the holder thereof) and it must be active. The user must enter the credentials of twitter.com and from that moment and he will be able to use the Service.</p>

            <p> 3. ABOUT THE SERVICE 1.5. The Service allows to access via a twitter.com account to Viral Get and to perform certain actions, such as search, classifications of search results, generate statistics, etc.. All actions performed on Twitter.com are made from the user's Twitter account and may be visible to other users of the platform twitter.com only if he or she decides to share the information. At any time, the user can log out of the service. 1.6. The User is solely responsible for the activity from his Twitter account through the service offered by the website. In that sense, the User acknowledges and accepts this and is solely responsible for actions taken with his Twitter.com account on this page. We know you will behave, but please, be responsible. 1.7. In using the Service, you agree to abide by the terms and conditions as the holder of Twitter.com. 1.8. The user may not use the service to carry out any illegal or contrary to law action especially those that are (i) a breach of the rules of intellectual property, (ii) a breach of data protection legislation, right to honor and privacy, (iii) Suppose a violation of the Terms and Conditions of Twitter.com. You also can not use the page in a way that can alter the normal functioning of it and for the purpose for which it was designed and made.</p>

            <p>4. REPORTS The service offers users the ability to generate (amazing) statistical reports on the activity of your session. The User assumes sole responsibility for this report and its uses. Therefore, the USER must have sufficient rights if necessary, to the intended use of the report (e.g. the publication of it or to share it in twitter.com or other platforms). In that sense, the User shall (i) enforce the Terms and Conditions set by Twitter.com over the content uploaded to the platform by other users, (ii) have the necessary rights to the generation and intended uses of this special report those relating to intellectual property, the right to honor and privacy and data protection.</p>

            <p>5. INTELLECTUAL AND INDUSTRIAL PROPERTY 1.9. As it is necessary to access the Service offered, VIRAL GET grants the User a non-exclusive personal use, revocable, non-assignable, and non-sublicensable to third parties license, on those elements of the Web page offered by VIRAL GET to Users that enable the enjoyment of the Service. The scope of the license is limited to the necessary use to access the service and is subject to compliance by the User of these Terms and Conditions. 1.10. The User agrees and undertakes to respect the rights of intellectual property of others in the use of the Service. The User guarantees that it is the author or has the rights to use the works and materials you can upload and use the web to use the Service. In the event that the user is not the author or does not have the rights necessary for the intended use thereof, must not use the work, names and third-party materials. 1.11. The service cannot be used to violate any rights of intellectual or industrial property of third parties.</p>

            <p>6. COOKIES 1.14. Cookies are text files that are hosted on the user's terminal with some information of the visit to the page. The User expressly accepts the installation of cookies by VIRAL GET and by from third parties for the provision of the services offered on the Website. For more information regarding Cookies, we offer the following links:  &bull; Entrada en Wikipedia sobre las cookies: http://es.wikipedia.org/wiki/Cookie_%28inform%C3%A1tica%29 &bull; Documento t&eacute;cnico explicativo sobre las cookies: http://tools.ietf.org/html/rfc6265 &bull; http://www.aboutcookies.org 1.15. Generally, browsers have different settings regarding cookies, you can adjust various levels of privacy, so that for example, refuse all cookies you can send a website like this or even eliminated all cookies that could have been saved. To modify these parameters, you can access the instructions of the browser you use or request help from the manufacturer. Anyway, VIRAL GET facilitates access to the instructions of the popular desktop browsers and mobile. &bull; Google Chrome, Mozilla Firefox, Internet Explorer y Safari. &bull; IOS, Android, Blackberry y Windows Phone. In the event that the user restricts or blocks any or all of the cookies of this website is possible that some of the functions or services provided on the page is unavailable.</p>

            <p>8. RIGHT OF WITHDRAWAL 1.17. The right of withdrawal is a power granted by law to the User which allows in certain occasions to leave without effect the contract, without having to justify its decision and without penalty of any kind. 1.18. The contract between the USER and TVIRAL GET is among the statutory exceptions established to the right of withdrawal, in which the service given by TWEET CATEGORY SL begins immediately after the engagement, so under Article 102 of the Law of Consumers and Users the right of withdrawal is not for application.</p>

            <p>9. AVAILABILITY OF SERVICE 9.1. The services offered through the Website depend on Twitter.com (i) is available and technically accessible, (ii) keep the terms of their respective API, especially the technical conditions, (iii) do not prevent the capture of information in the form and manner TWEET CATEGORY SL is done today. In the event that twitter.com is not available, changes their API or terms of use, VIRAL GET cannot guarantee the availability of the Service. The User understands and accepts the above situation inherent in the service provided by VIRAL GET so cannot be understood in any case that VIRALGET.com.ng has failed to provide service to the User who cannot claim any damages whatsoever against VIRAL GET by these circumstances. Meaning, we love Twitter, we truly do, but if it is down, we cannot work. 9.2. VIRAL GET will not be liable for breach of its obligations under these Terms and Conditions, where this is caused by interruptions in telecommunications services or electrical supply outside the holder, Hardware failures in running the page, or acts of God greater, such as flood, earthquake and other natural disasters, war, rebellion, sabotage, threats, blackmail or extortion, blockades, embargoes, strikes and lockouts occurred by social unrest and governments actions and omissions. 9.3. VIRAL GET without notice may terminate the Service viralget.com.ng to perform maintenance or improvements. Such interruptions in any case not generate any responsibility for VIRAL GET. 9.4. VIRAL GET will not be liable under any circumstances for the damages that service interruptions have caused to the User as described in the previous sections, and the fact that the user cannot access the Service temporarily does not generate any right to claim against VIRAL GET. But if this happens, please, talk to us and we will look for a solution.</p>

            <p>10. DISCLAIMER 1.19. In any case, VIRAL GET is not responsible for the activity performed by the user on the page or the reports that can be shared with other third parties. The User is solely responsible for the use made of the Service and the generated reports through the same. 1.20. VIRAL GET reserves the right to add new functionality to the Site or replace existing ones by others. In these cases, the User shall not claim any amount for the addition and / or replacement of the functionalities. But don't worry, we will add only cool features.</p>

            <p>11. TERMINATION OR SUSPENSION OF THE ACCOUNT 1.21. VIRAL GET reserves the right to terminate without notice the access to the Service in the event that the User (i) does not meet the conditions required by the Terms and Conditions for use (ii) impersonates another person, (iii) use the service for any illegal or criminal or fails, (iv) infringes any intellectual property rights or industrial in the contents that can upload to the Platform, (v) violates the rules of data protection, right to honor and privacy , (vi) not fulfilling the terms and conditions governing the service of twitter.com. (vii) Failing to comply with these Terms and Conditions. We don't like to say that, but please, don't be evil. 1.22. The suspension or cancellation of the account by any of the above reasons by VIRAL GET will not generate any compensation to the User.</p>

            <p> 12. MODIFICATION OF TERMS AND SERVICE 1.23. VIRAL GET reserves the right to modify these Terms and Conditions without having to make any prior notice to visitors and users of the site viralget.com.ng (But we will do our best to tell you guys). Every time the User uses the Service shall agree with the terms and conditions. In the event that the user does not agree with the new terms and conditions may unsubscribe from the service. 1.24. VIRAL GET reserves the right to modify the number and characteristics of the services offered through this page and in its case to suspend or discontinue providing the Service.</p>

            <p>13. OTHERS These Terms and Conditions shall be accessible to the user at all times, through a permanent link at the beginning of the page. VIRAL GET will not archive any electronic document formalizing the contract.</p>

            <p> 14. WAIVER OR RIGHTS The non-exercise of any right from VIRAL GET that may apply in accordance with these Terms and Conditions does not under any circumstances be construed as a waiver of that right and can be exercised by VIRAL GET whenever it has by convenient.</p>

            <p>15. TITLES MEANING The titles of the Provisions of these Terms and Conditions and, any of the sections that may exist in them, have a as meaning merely to clarify, or interpret or limit the scope of what established in each of these provisions and sections.</p>

            <p>16. SEVERABILITY Severability and / or complete any of the terms, covenants and / or provisions of these Terms and Conditions shall not affect the validity of the remaining contract.</p>

            <p>17. APPLICABLE LAW These Terms and Conditions shall be governed by Nigerian law, which will be applied in matters of the interpretation, validity and performance, unless a legal rule provides otherwise, in which case it will be regulated by that provision.</p>

            <p> 18. JURISDICTION The legal jurisdiction shall be determined by the laws that are applicable in the present legal relationship. If the choice of jurisdiction is legally possible and consequently there is no rule prohibiting the establishment of jurisdiction by the parties, all questions arising in connection with these Terms and Conditions of the service provided to through this site, are subject to the jurisdiction of the Courts of Nigeria.</p>

            <p>19. ATTRIBUTION AND ADVERTISING 1. VIRAL GET may display its or the &ldquo;Viral Get&rdquo; trademark(s) or logo(s) on the Online Information and/or through the provision of the Services and, if VIRAL GET does so, the user will not remove, modify, or interfere with the display or viewing of these trademarks or logos. 2. VIRAL GET may: Display the user's name, trademark(s) and/or logo(s) on the Online Information and/or through the provision of the Services or services similar to the services that are provided to other users of VIRAL GET, and/or otherwise (by any means), and disclose that the user uses the Service, in each case for marketing purposes and, where VIRAL GET does so, the user will not remove, modify, or interfere with the display or viewing of the same. 3.The user will display, and the user will not remove, alter or obscure, any attribution information provided by VIRAL GET in connection with the Services. </p>

        </div>

    </div>
    </div>
</header>

@endsection